name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary -t package/

      - name: Package Lambda function
        run: |
          cp lambda_function.py config.py package/
          cd package
          zip -r ../lambda_function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda get-function --function-name periodo-demonstrativo || \
          aws lambda create-function --function-name periodo-demonstrativo --runtime python3.8 --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambda_exec_role_NkIxpPdd --handler lambda_function.lambda_handler --zip-file fileb://lambda_function.zip --timeout 15
          
      - name: Wait for Lambda function creation
        run: |
          while [[ $(aws lambda get-function --function-name periodo-demonstrativo --query 'Configuration.State') == '"Pending"' ]]; do
            echo "Waiting for Lambda function to be created..."
            sleep 10
          done

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code --function-name periodo-demonstrativo --zip-file fileb://lambda_function.zip

      - name: Wait for Lambda function update
        run: |
          while [[ $(aws lambda get-function --function-name periodo-demonstrativo --query 'Configuration.LastUpdateStatus') == '"InProgress"' ]]; do
            echo "Waiting for Lambda function update to complete..."
            sleep 10
          done

      - name: Update Lambda function configuration
        run: |
          aws lambda update-function-configuration --function-name periodo-demonstrativo --timeout 15
